version: "3.7"

services:

    mongo:
        image: arm7/mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ~/docker/mongo:/data/db

    greenhouse_app:
        build: .
        privileged: true
        devices:
            - '/dev/:/dev/'
        restart: always
        command: tail -f /dev/null
        tty: true

    
